name: build
on:
  - push
  - pull_request
jobs:
  xgo:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.17.x
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          dest: build
          targets: linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          v: true
          ldflags: -s -w
          buildmode: default
      - name: Check
        run: |
          sudo apt-get -qq install tree
          tree -f -h build
