name: build
on:
  - push
  - pull_request
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.17.x
        target_os:
          - linux
          - darwin
        target_arch:
          - arm64
          - amd64
    env:
      BUILD_DIR: ./build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
      - name: Build
        run: |
          mkdir $BUILD_DIR
          GOOS=${{ matrix.target_os }} GOARCH=${{ matrix.target_arch }} \
            go build -o $BUILD_DIR/xalwart ./xalwart/main.go
      - name: Create an archive
        run: |
          tar -cvzf xalwart-cli.tar.gz LICENSE -C $BUILD_DIR xalwart
      - name: Upload the Artifact
        uses: actions/upload-artifact@v2
        with:
          name: xalwart-cli-${{ matrix.target_os }}-${{ matrix.target_arch }}.tar.gz
          path: xalwart-cli.tar.gz
          retention-days: 7
