name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    uses: YuriyLisovskiy/xalwart-cli/.github/workflows/build.yml@master
    with:
      app_name: xalwart
      release: true
  create_release:
    needs: build
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Create release notes
        run: |
          git log $(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))..${{ steps.tag_name.outputs.SOURCE_TAG }} --oneline > ./release-notes.txt
          test -s ./release-notes.txt && printf '%s\n%s\n\n' "## Changelog" "$(cat ./release-notes.txt)" > ./release-notes.txt
          echo 'To explore all features of this application release, check out the [documentation](https://github.com/YuriyLisovskiy/xalwart-cli/wiki).' >> ./release-notes.txt
          cat ./release-notes.txt
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./archives
      - name: Display structure of downloaded files
        run: ls -R
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_name.outputs.SOURCE_TAG }}
          body_path: ./release-notes.txt
          draft: false
          prerelease: false
          files: |
            ./archives/*/*.tar.gz
