name: release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    name: Build the App for Target Platforms
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.17.x
        target_os:
          - linux
          - darwin
        target_arch:
          - arm64
          - amd64
    env:
      BUILD_DIR: ./build
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
      - name: Build
        run: |
          mkdir -p $BUILD_DIR
          GOOS=${{ matrix.target_os }} GOARCH=${{ matrix.target_arch }} \
            go build -o $BUILD_DIR/xalwart ./xalwart/main.go
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Create an archive
        run: |
          tar -cvzf xalwart-cli-${{ steps.tag_name.outputs.SOURCE_TAG }}-${{ matrix.target_os }}-${{ matrix.target_arch }}.tar.gz \
              LICENSE -C $BUILD_DIR test
      - name: Upload an archive to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xalwart-cli-${{ steps.tag_name.outputs.SOURCE_TAG }}-${{ matrix.target_os }}-${{ matrix.target_arch }}
          path: xalwart-cli-${{ steps.tag_name.outputs.SOURCE_TAG }}-${{ matrix.target_os }}-${{ matrix.target_arch }}.tar.gz
          retention-days: 1
  create_release:
    needs: build
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Create changelog
        run: |
          echo '## Changelog' > ./release-changelog.txt
          echo "" >> ./release-changelog.txt
          git log $(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))..${{ steps.tag_name.outputs.SOURCE_TAG }} --oneline >> ./release-changelog.txt
          cat ./release-changelog.txt
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./archives
      - name: Display structure of downloaded files
        run: ls -R
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_name.outputs.SOURCE_TAG }}
          body_path: ./release-changelog.txt
          draft: false
          prerelease: false
          files: |
            ./archives/*/*.tar.gz
