name: Tests
on:
  push:
    branches:
      - '!v*.*.*'
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version:
          - 1.17.x
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
      - uses: actions/checkout@v2
      - name: Run tests
        run: go test ./...
  build:
    uses: YuriyLisovskiy/xalwart-cli/.github/workflows/build.yml@${GITHUB_REF#refs/heads/}
    with:
      tag: ${GITHUB_REF#refs/heads/}
      app_name: xalwart
