name: Tests
on:
  push:
    branches:
      - '*'
      - '!v*.*.*'
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version:
          - 1.17.x
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
      - uses: actions/checkout@v2
      - name: Run tests
        run: go test ./...
  build:
    name: Build the App
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.17.x
        target_os:
          - linux
          - darwin
        target_arch:
          - arm64
          - amd64
    env:
      BUILD_DIR: ./build
      ARCHIVE_PREFIX: xalwart-cli
      APP_NAME: xalwart
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
      - name: Build
        run: |
          mkdir -p $BUILD_DIR
          GOOS=${{ matrix.target_os }} GOARCH=${{ matrix.target_arch }} \
            go build -o $BUILD_DIR/${{ env.APP_NAME }} ./xalwart/main.go
      - name: Create an archive
        run: |
          tar -cvzf ${{ env.ARCHIVE_PREFIX }}-${{ matrix.target_os }}-${{ matrix.target_arch }}.tar.gz \
              LICENSE -C $BUILD_DIR ${{ env.APP_NAME }}
      - name: Upload an archive to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARCHIVE_PREFIX }}-${{ matrix.target_os }}-${{ matrix.target_arch }}
          path: ${{ env.ARCHIVE_PREFIX }}-${{ matrix.target_os }}-${{ matrix.target_arch }}.tar.gz
          retention-days: 7
