# Simple configuration for quick check the application.
#
# CMake configuration log and build log are available
# in /var/log/app after building the container as configure.log
# and build.log respectfully.

FROM <% .FrameworkBaseDockerImage %>

ENV WORK_DIR=/app

# Set the working directory.
WORKDIR $WORK_DIR

# Copy project files.
COPY CMakeLists.txt ./
COPY ./src ./src

# Create directories for build files and logs.
RUN mkdir -p ./build && mkdir -p /var/log/app

# Configure and build the application.
# Remark: to make the database changes persistent use PostgreSQL or another database with a server.
#         For using PostgreSQL add '-D XW_USE_POSTGRESQL=yes' option.
RUN cd ./build && \
    cmake -D CMAKE_C_COMPILER=clang \
          -D CMAKE_CXX_COMPILER=clang++ \
          -D CMAKE_BUILD_TYPE=Release \
          -D XW_USE_SQLITE3=yes \
          .. \
          2>&1 | tee /var/log/app/configure.log && \
    make application 2>&1 | tee /var/log/app/build.log

WORKDIR $WORK_DIR

# Copy compiled app and YAML configurations to the working directory.
RUN cp ./build/application ./ && cp ./src/*.yaml ./

# Clean up the working directory.
RUN rm -rf ./CMakeLists.txt ./src ./build

CMD ["bash"]
